In [3]:
import numpy as np
import pandas as pd

In [4]:
df= pd.read_csv('customer.csv')
df.sample(4)

age  gender   review education purchased
24   16  Female  Average        PG       Yes
37   94    Male  Average        PG       Yes
36   34  Female     Good        UG       Yes
47   38  Female     Good        PG       Yes

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)


In [30]:
y_test

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
y_train
# this is only applicable to output data

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [24]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
le.fit(y_train)
le.classes_
y_train=le.transform(y_train)
y_test=le.transform(y_test)
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [26]:
y_test

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0])